version: '3'

services:

  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    restart: always
    environment:
      - 'POSTGRES_USERS = postgres'
      - 'POSTGRES_PASSWORD=pass'

  app:
   build: ./
   container_name: 'java-app'
   ports:
     - "8080:8080"
